### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by GreatAlexander** [ipab-rad/ros_myo#1]
ESSENTIAL:
- [x] Open two Serial ports on same machine for both Myos (Come on man!)
- [x] Port old ros_myo code to work with new Myo Data
- [x] Test gesture recognition for grasping
- [ ] Setup torque averaging for vibration feedback
- [ ] Start Baxter arm with rotated wrist 

OPTIONAL:
- [ ] Figure out the Bluetooth method for calling different levels of vibration strength/duration
